name: react deploy
on: [push]

jobs:
  build:
    name: hello github action
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@master

      - name: echo hello
        run: echo "hello"
