services:
  ganache:
    build:
      context: "./contract"
      dockerfile: "Dockerfile_ganache"
    container_name: "ganache"
    ports:
      - "7545:7545"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "./key:/app/key"

  truffle:
    depends_on:
      - ganache
    build:
      context: "./contract"
      dockerfile: "Dockerfile_truffle"
    container_name: "truffle"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "./truffle_build:/app/build"
    ports:
      - "4005:4005"

  node:
    depends_on:
      - truffle
    build: "./server"
    container_name: "node"
    ports:
      - "443:443"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "./truffle_build/contracts:/usr/src/app/src/blockchain/contract_json"
      - "./key:/usr/src/app/src/config/key"
    restart: always
