services:
  ganache:
    build: "./contract"
    container_name: "ganache_truffle"
    restart: "always"
    ports:
      - "7545:7545"
    extra_hosts:
      - host.docker.internal:host-gateway

  node:
    build: "./server"
    restart: "always"
    container_name: "melon_node"
    ports:
      - "443:443"
    extra_hosts:
      - host.docker.internal:host-gateway
