#truffle
FROM node:16

ENV DOCKERIZE_VERSION v0.2.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \  
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

WORKDIR /app

COPY package*.json ./

RUN npm i
# RUN apk add --no-cache --upgrade bash

COPY truffle-config.js ./
COPY contracts ./contracts
COPY migrations ./migrations
COPY test ./test
COPY setting.sh ./

EXPOSE 4005

RUN ["chmod", "+x", "/app/setting.sh"]

ENTRYPOINT ["/app/setting.sh"] 
