name: react deploy
on:
  push:
    branches:
      - main
      - dev
    paths:
      - client

jobs:
  build:
    name: react-project build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: "./client"
    steps:
      - name: checkout code
        uses: actions/checkout@v3.3.0

      - name: cache dependency
        uses: actions/cache@v3.2.3
        with:
          path: node_modules
          key: ${{runner.os}}-build-${{hashFiles('**/package-lock.json')}}
          restore-key: |
            ${{runner.os}}-build-
            ${{runner.os}}-

      - name: install dependency
        run: npm i

      - name: build project
        run: npm run build

      - name: s3 upload
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://dmreactdeploy
