name: react deploy
on:
  push:
    branches:
    - main
    - dev
    paths:
    - client

jobs:
  build:
    name: react-project build
    runs-on: ubuntu-20.04
    defaults:
      run: 
        working-directory: "./client"
    steps:
      - name: checkout code
        uses: actions/checkout@v3.3.0

      - name: install dependency
        run: npm i
        
      - name: build project
        run : npm run build
